Implement crud Operations
rosemutai/To-Do-List pull request #2
Opened 2023-03-29 19:07 UTC by rosemutai

- Implemented a function for adding a new task to the list of existing tasks.
- Implemented a function for deleting a task.
- Implemented a function for editing task descriptions.
- Store tasks in local storage

2023-03-29 20:09 UTC, frank1738 requested changes
Hi @rosemutai , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>


## Highlights

✅ Correct use of Github workflow
✅ No linter error


## Required Changes ♻️
- [x] If you have not deployed the project yet, I think it would be better to indicate that the `live demo` link is not available. Having broken links on your readme file hinders user experience: If users encounter broken links in the README file, they may become frustrated and give up on using the software. This can harm the adoption of the project and lead to a decrease in its popularity.

_Check the comments under the review._

## Optional suggestions

N/A
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 20:09 UTC, frank1738 commented on src/modules/Todo.js
> +};
#### Good work displaying the tasks but there are some aspects you can improve
- [ ] As stated in the project requirement, Kindly ensure that - By default new tasks should have the property `completed` set to `false` and the property `index` set to the value of the new array length (i.e. if you're adding a 5th task to the list, the index of that task should equal to 5).

![image](https://user-images.githubusercontent.com/98453979/228654460-11a98234-d261-4a2c-87f9-c85f94a15d2a.png)

- I tried clicking on the `three doted icon` on your design and I noted the tasks were being deleted but that could only be displayed after I refresh the page. Kindly try following [this](https://www.youtube.com/watch?v=AcUd-_Yjjqg) video to guide you on how to implement the delete functionality. Also note that deleting a task should update all remaining items' indexes, so they represent the current list order and are unique(i.e. if you're deleting the first task index 1 from the list, the index of the next task(2) should set to 1).
- I could not edit your tasks. Kindly ensure that all your tasks can be edited and change saved in the local storage as stated in the project requirement

![image](https://user-images.githubusercontent.com/98453979/228655134-1c5d0590-e980-4724-bbc0-720f17ac61c5.png)

2023-03-30 16:59 UTC, ishimwezachee requested changes
Hi @rosemutai , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![image](https://user-images.githubusercontent.com/43877689/228910395-29d31a32-347b-4a50-a792-722df719e024.png)


 ## Highlights
✅  Project is running successfully 
✅ No linter error

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [OPTIONAL ] I recommend you to use the correct gitflow, for this  project is individual project, the base branch should  be `dev `branch not `main `branch 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 16:59 UTC, ishimwezachee commented on src/modules/Todo.js
> +};
- [ ]  As previous reviewer suggested, you still have some tasks that are true by default. while they should be true only if the user check the tasks as done. 
![image](https://user-images.githubusercontent.com/43877689/228908327-1790f794-b7fe-4275-809b-e1cdb6a37f69.png)

2023-03-30 16:59 UTC, ishimwezachee commented on src/modules/Todo.js
> +const editToDoList = (index, newValue) => {
- [ ]  As previous reviewer suggested the functions for `editing `and `deleting `the task should work as expected. at this moment a user can not edit or delete a created task. pleasure check the requirements those functions as suggested as well.

2023-03-31 05:51 UTC, shella12 approved these changes
Hi @rosemutai , 

## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Linters are passing ✔️ 
- README is professional 👍 
- Great UI 🥇 
- Implemented all requirements 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 05:52 UTC, merged